name: Vercel Preview Deployment
on:
  push:
    branches-ignore:
      - main
jobs:
  job1: 
    name: Run Tests
    uses: ./.github/workflows/test_on_push.yaml

  job2: 
    name: Deploy Preview
    needs: job1
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      environment: preview
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}