name: Run tests on any Push event
on: push
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
    # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r python-client/requirements.txt
      - name: Run tests
        run: coverage run python-client/api/tests.py
      - name: Tests report
        run: coverage report